name: Docker Image CI

on:
  release:
    types: [created]

jobs:

  build_and_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag sammeeeee/cron-curl:${{ github.event.release.tag_name }}
        docker tag sammeeeee/cron-curl:${{ github.event.release.tag_name }} sammeeeee/cron-curl:latest
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.KEY }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push image to Docker Hub
      run: |
        docker push sammeeeee/healthcheck-curl:${{ github.event.release.tag_name }}
        docker push sammeeeee/healthcheck-curl:latest